name: Automate deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 14
    - name: Building an application
      run: |
        npm install
        npm run build
    - name: Commit and push to gh-pages
      run: |
        git config user.name "Nakorn Sinpadung"
        git config user.email "nakorndev@gmail.com"
        git checkout --orphan gh-pages
        git reset
        git add docs/* --force
        git commit -m "Deploy to GitHub Pages"
        git push --force origin gh-pages
